name: GitHub Actions Demo
on: [push]
jobs:
  HTMLProofer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v2
        with:
          path: tmp/.htmltest
          key: ${{ runner.os }}-htmltest
      - name: htmltest-action
        uses: wjdp/htmltest-action@v0.13.0-rc1

# - uses: actions/cache@v2
#   with:
#     path: tmp/.htmltest
#     key: ${{ runner.os }}-htmltest

# - name: HTML Test
#   run: |
#     curl https://htmltest.wjdp.uk | bash
#     bin/htmltest
