name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: HTML5Validator
        uses: Cyb3r-Jak3/html5validator-action@v7.1.1
        with:
          root: tests/
