name: learn-github-actions
on: [push]
jobs:
 Validate-HTML:
  runs-on: ubuntu-latest
  steps:
  - name: Set up Python
    uses: actions/setup-python@v4
    with:
      python-version: '3.10'
  - name: Install dependencies
    run:  pip install html5validator
  - name: Check content 
    run:  cd .. && cd ..
  - name: Check content 
    run:  ls
  - name:  Run Script
    run: |
       html5validator --root _build/
    working-directory: _build/
